### ISSUE TITLE
Causes issue with lockscreen on Pop!_OS 22.04

### ISSUE THREAD

**Issue by thomastubby** [cwittenberg/thisipcan.cyou#1] opened 2022-12-14 02:24 UTC
After installation activation and only once VPN is activated, pressing the shortcut keys to lock the system will cause the system to hang and keyboard input is no longer registered. The mouse can no longer be used to close tabs. System acts as if invisible wall is placed between user and system, almost as if lockscreen is there but unusable. Also, closing lid of laptop (where OS is installed) and reopening lid unlocks device again with no lockscreen and user can resume using their device. This is a huge security concern as it can be used to bypass the lockscreen consistently. Once uninstalled, issue is no longer present. Otherwise, love this addon. Please fix.

**Comment by cwittenberg** [comment] 2023-01-02 09:35
Thank you for reporting this @thomastubby. It really took me awhile to figure out what caused the issue

**Issue**
GNOME Lockscreen procedure not completing when extension is active

**Cause**
The lockscreen procedure causes the extension to trigger the disable routine, which triggered an unload of all message tray notifications - which have an embedded reference to an icon. The icon was not set due to a missing constructor argument to the GNOME Messagetray Source constructor. As a result, the lockscreen routine tried to unload a nullpointer - which caused the lockscreen procedure to fail, resulting in a 'brainfreeze' after initiating CTRL+L in GNOME or otherwise triggering the lockscreen

**Solution**
Specify correct constructor argument to GNOME Messagetray Source call.

The issue is fixed in v15 of the extension - which was just accepted by the GNOME foundation. Please update and retest, let me know if the issue is now fixed for you - i'll close the issue when confirmed. Feedback you can also mail me at: [gnome@ipcan.cyou](mailto:gnome@ipcan.cyou)

**Comment by thomastubby** [comment] 2023-01-03 18:52
Extension works as expected, thanks!

**Closed as completed** 2023-01-03 18:53 UTC
